#!/bin/bash

if [ $# -ne 1 ]; then
    APP_NAME="$(basename $0)"
    echo "${APP_NAME}: Stops/destroys a defined libvirt domain"
    echo "${APP_NAME}: Usage is: ${APP_NAME} {DOMAIN_NAME}"
    echo -e "DOMAIN_NAME: libvirt domain name"
    exit 1
fi

virsh -c qemu:///system destroy "$1"
