#!/bin/bash

#     --machine virt,virtualization=true,kernel_irqchip=on,gic-version=3 \#
#     --qemu-commandline="-d unimp,guest_errors -serial mon:stdio" \

# --features acpi=off \
# --features gic.version=2 \
	
LIBVIRT_DEBUG=1 virt-install \
    --connect qemu:///system \
    --virt-type qemu \
    -n debian-stable \
    --install no_install=yes \
    --noreboot \
    --arch aarch64 \
    --machine virt \
    --features acpi=off \
    --cpu cortex-a53\
    --memory 1024 \
    --graphics none \
    --boot kernel=/opt/vbox/media/shared/dev/debian-runner/debian-stable-qemu/data/boot/vmlinuz-6.1.0-18-arm64,initrd=/opt/vbox/media/shared/dev/debian-runner/debian-stable-qemu/data/boot/initrd.img-6.1.0-18-arm64,kernel_args="root=/dev/mapper/rootvg-root console=ttyAMA0 consoleblank=0 elevator=noop scsi_mod.use_blk_mq=Y net.ifnames=0 biosdevname=0 - DEBIAN_FRONTEND=text" \
    --network default \
    --rng /dev/urandom \
    --clock offset=utc \
    --filesystem /opt/vbox/media/shared/dev/debian-runner/debian-stable-qemu/data,shared \
    --disk /opt/vbox/media/shared/dev/debian-runner/debian-stable-qemu/sys_boot.img,size=0.5 \
    --disk /opt/vbox/media/shared/dev/debian-runner/debian-stable-qemu/sys_1.img,size=1.5
