#!/bin/bash

#     --machine virt,virtualization=true,kernel_irqchip=on,gic-version=3 \#
#     --qemu-commandline="-d unimp,guest_errors -serial mon:stdio" \

# --features acpi=off \
# --features gic.version=2 \

export VIRT_NAME="debian-stable"
export QEMU_ARCH="x86_64"
export QEMU_MACH="q35"
export QEMU_CPU="qemu64"
export QEMU_MEM="1024"

./mkvirt_kboot
