#!/bin/bash
ME="${BASH_SOURCE[0]}"
MYDIR="$(cd "$(dirname "${ME}")" && pwd)"

BOXNAME="${1}"
shift
IMAGE="image-vagrant/${BOXNAME}"
mkdir -p "${IMAGE}"

for img in "$@"; do
    cp "${img}" "${IMAGE}/${img}"
done
cd "${MYDIR}/vagrant"
cp -a * "${IMAGE}"

cd "${IMAGE}"
shopt -s extglob
METADATA_JSON="$(cat metadata.json|jq '. += {disks: []}')"
for img in sys_boot.img !(sys_boot.img|metadata.json|Vagrantfile|"$ME"); do
    METADATA_JSON="$(echo $METADATA_JSON|jq '.disks += [$ARGS.named]' --arg path $img)"
done
echo "$METADATA_JSON" >metadata.json

echo cat metadata.json
cat metadata.json
echo cat Vagrantfile
cat Vagrantfile
pwd
tar -cvzf "../${BOXNAME}.box" .
cd ..
rm -rf "${IMAGE}"
md5sum * >.MD5SUMS
mv .MD5SUMS MD5SUMS
